const STORE = 'gaming_arena_v3';
const MODES = ['BR Solo','BR Duo','BR Squad','CS 1v1','CS 2v2','CS 3v3','CS Squad','Lone Wolf 1v1','Lone Wolf 2v2'];
const seed = {
  session: null,
  user: {id:'u1',name:'Demo Player',email:'user@example.com',uid:'',played:3,kills:21,wins:1,winnings:450,balance:120},
  tournaments: [
    {id:'GA-1042',mode:'BR Solo',name:'Night Rush #42',status:'upcoming',start:'Today • 8:30 PM',entry:30,kill:10,prize:700,total:48,taken:31,roomId:'—',roomPass:'—'},
    {id:'GA-1038',mode:'BR Solo',name:'Arena Open #38',status:'live',start:'Live now',entry:50,kill:15,prize:1200,total:48,taken:48,roomId:'874912',roomPass:'A7Z2'},
    {id:'GA-1031',mode:'BR Duo',name:'Duo Thunder #31',status:'upcoming',start:'Tomorrow • 7:00 PM',entry:40,kill:12,prize:900,total:24,taken:14,roomId:'—',roomPass:'—'},
    {id:'GA-1027',mode:'BR Squad',name:'Squad Wars #27',status:'upcoming',start:'Tomorrow • 9:30 PM',entry:80,kill:20,prize:1800,total:12,taken:8,roomId:'—',roomPass:'—'},
    {id:'GA-1019',mode:'CS 1v1',name:'Clash Duel #19',status:'live',start:'Live now',entry:20,kill:0,prize:350,total:32,taken:32,roomId:'991723',roomPass:'DUEL'},
    {id:'GA-1014',mode:'CS 2v2',name:'Duo Clash #14',status:'upcoming',start:'Oct 1 • 6:30 PM',entry:35,kill:0,prize:650,total:20,taken:11,roomId:'—',roomPass:'—'},
    {id:'GA-1008',mode:'CS 3v3',name:'Triple Threat #8',status:'upcoming',start:'Oct 1 • 8:00 PM',entry:50,kill:0,prize:900,total:16,taken:10,roomId:'—',roomPass:'—'},
    {id:'GA-1005',mode:'CS Squad',name:'Squad Clash #5',status:'result',start:'Sep 29 • 9:00 PM',entry:70,kill:0,prize:1500,total:12,taken:12,roomId:'',roomPass:''},
    {id:'GA-1002',mode:'Lone Wolf 1v1',name:'Lone Wolf Rush #2',status:'upcoming',start:'Oct 2 • 7:30 PM',entry:25,kill:0,prize:450,total:40,taken:29,roomId:'—',roomPass:'—'},
    {id:'GA-0999',mode:'Lone Wolf 2v2',name:'Lone Wolf Duo #9',status:'result',start:'Sep 28 • 8:00 PM',entry:40,kill:0,prize:700,total:24,taken:24,roomId:'',roomPass:''}
  ],
  joined: [
    {tId:'GA-1038',status:'live',slot:17,uid:'1234567890',joinedAt:'Today'},
    {tId:'GA-1014',status:'upcoming',slot:9,uid:'1234567890',joinedAt:'Yesterday'}
  ],
  transactions:[{type:'Credit',amount:120,details:'Demo opening balance',status:'completed',date:'Today'}],
  withdrawals:[],
  deposits:[],
  results:[
    {tId:'GA-1005',title:'Squad Clash #5',position:1,prize:800,kills:9,date:'Sep 29'},
    {tId:'GA-0999',title:'Lone Wolf Duo #9',position:6,prize:0,kills:3,date:'Sep 28'}
  ],
  admin:{upi:'gamingarena@upi',email:'admin@gamingarena.local',telegram:'@gamingarena_support'},
  notifications:[
    {id:'n1',type:'admin',title:'Welcome to Gaming Arena',message:'New Free Fire tournaments and slot updates will appear here.',time:Date.now()-3600000,read:false},
    {id:'n2',type:'wallet',title:'Wallet verification',message:'Top-ups and withdrawals stay pending until admin approval.',time:Date.now()-1800000,read:false}
  ],
  contestChats:{
    'GA-1038':[{id:'m1',from:'admin',name:'Admin',message:'Welcome players! Room ID and password will be shared before the match.',time:Date.now()-20*60*1000}],
    'GA-1014':[{id:'m2',from:'admin',name:'Admin',message:'Please join the room 5 minutes before start.',time:Date.now()-40*60*1000}]
  }
};
function load(){try{const raw=localStorage.getItem(STORE);return raw?JSON.parse(raw):structuredClone(seed)}catch(e){return structuredClone(seed)}}
let db=load();
function save(){localStorage.setItem(STORE,JSON.stringify(db))}
function ensureDataModel(){
  if(!Array.isArray(db.notifications)) db.notifications=structuredClone(seed.notifications);
  db.tournaments=(db.tournaments||[]).map((t,i)=>{
    if(!t.startAt){
      const offset=i===0?45:i===1?(-15):24*(i+1);
      t.startAt=new Date(Date.now()+offset*60*1000).toISOString();
    }
    if(!Number.isFinite(t.lastSlotNotice)) t.lastSlotNotice=0;
    return t;
  });
  db.joined=db.joined||[]; db.deposits=db.deposits||[]; db.withdrawals=db.withdrawals||[]; db.transactions=db.transactions||[]; db.contestChats=db.contestChats||{};
  db.tournaments=(db.tournaments||[]).map(t=>{
    if(!t.chart){
      t.chart={rounds:[
        {id:'r1',name:'Round 1',matches:[
          {id:'m1',a:'Team Alpha',b:'Team Bravo',as:16,bs:8,status:t.status==='live'?'live':'scheduled'},
          {id:'m2',a:'Team Charlie',b:'Team Delta',as:14,bs:10,status:'scheduled'},
          {id:'m3',a:'Team Echo',b:'Team Foxtrot',as:12,bs:6,status:'scheduled'},
          {id:'m4',a:'Team Goku',b:'Team Hunter',as:18,bs:5,status:'scheduled'}
        ]},
        {id:'r2',name:'Round 2',matches:[
          {id:'m5',a:'Team Alpha',b:'Team Charlie',as:16,bs:7,status:'scheduled'},
          {id:'m6',a:'Team Echo',b:'Team Goku',as:12,bs:9,status:'scheduled'}
        ]},
        {id:'sf',name:'Semifinal',matches:[
          {id:'m7',a:'Team Alpha',b:'Team Echo',as:18,bs:11,status:'scheduled'},
          {id:'m8',a:'Team Charlie',b:'Team Goku',as:14,bs:16,status:'scheduled'}
        ]},
        {id:'final',name:'Final',matches:[
          {id:'m9',a:'Team Alpha',b:'Team Goku',as:18,bs:12,status:'scheduled'}
        ]}
      ],leaderboard:[
        {name:'Team Alpha',kills:32,points:80,position:1},
        {name:'Team Goku',kills:28,points:72,position:2},
        {name:'Team Hydra',kills:25,points:65,position:3},
        {name:'Team Insane',kills:22,points:58,position:4},
        {name:'Team TSG',kills:20,points:52,position:5}
      ],updatedAt:null};
    }
    return t;
  });
}
ensureDataModel();
function notify(type,title,message,extra={}){
  ensureDataModel();
  const n={id:'N'+Date.now()+Math.floor(Math.random()*1000),type,title,message,time:Date.now(),read:false,...extra};
  db.notifications.unshift(n); db.notifications=db.notifications.slice(0,80); save();
}
function notificationIcon(type){return ({admin:'◆',tournament:'🏆',join:'✓',wallet:'◒',withdraw:'↗',reminder:'⏰',slots:'◉'}[type]||'•')}
function formatTime(ts){return new Date(ts).toLocaleString([], {day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'})}
function tournamentStart(t){return t.startAt?new Date(t.startAt):null}
function upcomingReminderCheck(){
  if(!db.session || db.session.role!=='user') return;
  const now=Date.now(); ensureDataModel();
  db.joined.forEach(j=>{
    const t=db.tournaments.find(x=>x.id===j.tId); if(!t||!t.startAt) return;
    const start=new Date(t.startAt).getTime(); const diff=start-now;
    if(diff>0 && diff<=10*60*1000 && diff>=0){
      const key='reminder:'+t.id;
      if(!db.notifications.some(n=>n.key===key)) notify('reminder','Tournament starts in 10 minutes',`${t.name} starts soon. Your slot is ${j.slot}.`,{key,tId:t.id});
    }
  });
}
function slotUpdateCheck(){
  ensureDataModel();
  db.tournaments.forEach(t=>{
    const available=Math.max(t.total-t.taken,0); const threshold=available<=5?5:available<=10?10:0;
    if(threshold && t.lastSlotNotice!==threshold){
      t.lastSlotNotice=threshold;
      notify('slots','Slots are filling up',`${t.name} has only ${available} slot${available===1?'':'s'} left.`,{tId:t.id});
    }
  });
}
setInterval(()=>{upcomingReminderCheck();slotUpdateCheck();},15000);
function money(n){return `₹${Number(n||0).toFixed(0)}`}
function el(html){const t=document.createElement('template');t.innerHTML=html.trim();return t.content.firstElementChild}
function mount(node){const app=document.querySelector('#app');app.innerHTML='';app.appendChild(node)}
function toast(msg){const t=document.querySelector('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.__tt);window.__tt=setTimeout(()=>t.classList.remove('show'),2200)}
function icon(name,size=18){const m={home:'⌂',contest:'◈',wallet:'◒',profile:'◉',bell:'◌',back:'‹',plus:'＋',close:'×',lock:'⌾',support:'?',admin:'◆',search:'⌕'};return `<span style="font-size:${size}px;line-height:1">${m[name]||'•'}</span>`}
function unreadCount(){return (db.notifications||[]).filter(n=>!n.read).length}
function topbar(title,sub=''){return `<header class="topbar"><div class="topbar-inner"><div class="brand"><span class="brand-mark">GA</span><div>${title}<div class="small">${sub}</div></div></div><button class="icon-btn notify-btn" onclick="renderNotifications()">${icon('bell',18)}${unreadCount()?`<span class="notify-badge">${unreadCount()>9?'9+':unreadCount()}</span>`:''}</button></div></header>`}
function bottomNav(active){return `<nav class="bottom-nav"><div class="bottom-nav-inner">
  <button class="nav-btn ${active==='home'?'active':''}" onclick="go('home')">${icon('home',20)}<span>Home</span></button>
  <button class="nav-btn ${active==='contests'?'active':''}" onclick="go('contests')">${icon('contest',20)}<span>My Contests</span></button>
  <button class="nav-btn ${active==='wallet'?'active':''}" onclick="go('wallet')">${icon('wallet',20)}<span>Wallet</span></button>
  <button class="nav-btn ${active==='profile'?'active':''}" onclick="go('profile')">${icon('profile',20)}<span>Profile</span></button>
</div></nav>`}
function requireAuth(){if(!db.session){renderAuth();return false}return true}
function go(page){if(!requireAuth())return; if(page==='home')renderHome(); if(page==='contests')renderContests(); if(page==='wallet')renderWallet(); if(page==='profile')renderProfile(); if(page==='notifications')renderNotifications();}
function renderAuth(mode='login',forgot=false){
  const node=el(`<div class="auth"><div class="auth-card"><div class="brand" style="margin-bottom:16px"><span class="brand-mark">GA</span><span>Gaming Arena</span></div><div class="tabs"><button class="tab ${!forgot&&mode==='login'?'active':''}" onclick="renderAuth('login')">Login</button><button class="tab ${!forgot&&mode==='register'?'active':''}" onclick="renderAuth('register')">Register</button></div><div id="authForm"></div></div></div>`);
  if(forgot){node.querySelector('#authForm').innerHTML=`<h1>Reset password</h1><p class="auth-sub">Enter your email. We’ll generate a demo OTP for verification.</p><div class="field"><label>Email</label><input id="otpEmail" type="email" placeholder="you@example.com"></div><button class="btn btn-primary btn-wide" onclick="sendOtp()">Send OTP</button><div style="margin-top:16px"><a href="#" class="link" onclick="renderAuth('login');return false">Back to login</a></div>`}
  else if(mode==='login')node.querySelector('#authForm').innerHTML=`<h1>Welcome back</h1><p class="auth-sub">Enter your account details to continue to tournaments.</p><div class="field"><label>Email</label><input id="loginEmail" value="user@example.com" type="email"></div><div class="field"><label>Password</label><input id="loginPass" value="123456" type="password"></div><div class="row" style="margin:8px 0 16px"><span class="small">Demo: user@example.com / 123456</span><a href="#" class="link" onclick="renderAuth('login',true);return false">Forgot password?</a></div><button class="btn btn-primary btn-wide" onclick="login()">Login</button>`;
  else node.querySelector('#authForm').innerHTML=`<h1>Create account</h1><p class="auth-sub">Join tournaments, manage your wallet and track your results.</p><div class="field"><label>Name</label><input id="regName" placeholder="Your name"></div><div class="field"><label>Email</label><input id="regEmail" type="email" placeholder="you@example.com"></div><div class="field"><label>Password</label><input id="regPass" type="password" placeholder="At least 6 characters"></div><button class="btn btn-primary btn-wide" onclick="register()">Create account</button>`;
  mount(node)
}
function login(){db.session={email:document.querySelector('#loginEmail').value,role:document.querySelector('#loginEmail').value==='admin@gamingarena.local'?'admin':'user'};if(db.session.role==='admin'){save();renderAdmin();return}save();toast('Welcome back!');renderHome()}
function register(){const name=document.querySelector('#regName').value.trim()||'New Player';const email=document.querySelector('#regEmail').value.trim();if(!email)return toast('Enter an email');db.user.name=name;db.user.email=email;db.session={email,role:'user'};save();toast('Account created');renderHome()}
function sendOtp(){const email=document.querySelector('#otpEmail').value.trim();if(!email)return toast('Enter your email');showModal('Verify OTP',`<div class="alert">Demo OTP: <b>482916</b> — in production this would be sent by email.</div><div class="field"><label>OTP</label><input id="resetOtp" placeholder="6-digit OTP"></div><div class="field"><label>New password</label><input id="resetPass" type="password" placeholder="New password"></div><button class="btn btn-primary btn-wide" onclick="verifyReset()">Reset password</button>`)}
function verifyReset(){if(document.querySelector('#resetOtp').value!=='482916')return toast('Invalid OTP');closeModal();toast('Password reset successfully')}
function renderHome(){
  mount(el(`<div class="mobile-shell">${topbar('Home','Gaming Arena')}<main class="page">
    <section class="hero hero-home" onclick="openFreeFireModes()">
      <div class="hero-top"><div>
        <div class="tag">GAME HUB</div>
        <h1>Free Fire</h1>
        <p>Enter the arena and choose your contest mode.</p>
      </div><div class="balance-pill">${money(db.user.balance)}</div></div>
      <div class="freefire-visual"><div class="ff-emblem">FF</div><div><b>FREE FIRE</b><span>Battle. Compete. Win.</span></div><span class="arrow">›</span></div>
      <button class="btn btn-primary btn-wide" onclick="event.stopPropagation();openFreeFireModes()">Open Free Fire</button>
    </section>

    <div class="section-head"><div><h2>Game</h2><p>One game, all contest modes</p></div></div>
    <div class="panel home-info"><div class="info-icon">◈</div><div><b>Free Fire tournaments</b><p>Live matches, upcoming tournaments and published results.</p></div></div>
  </main>${bottomNav('home')}</div>`));
}
function openFreeFireModes(){
  mount(el(`<div class="mobile-shell">${topbar('Free Fire','Choose your contest mode')}<main class="page">
    <button class="back-link" onclick="renderHome()">${icon('back',20)} Back to Home</button>
    <section class="section-banner"><div><div class="tag">FREE FIRE</div><h1>Choose a mode</h1><p>Open a mode to view Live, Upcoming and Results.</p></div><div class="ff-emblem big">FF</div></section>
    <div class="mode-card-grid">${MODES.map((m,i)=>`<button class="mode-card" onclick="showModePage('${m.replace(/'/g,"\\'")}')"><span class="mode-index">${String(i+1).padStart(2,'0')}</span><span class="mode-name">${m}</span><span class="mode-arrow">›</span></button>`).join('')}</div>
  </main>${bottomNav('home')}</div>`));
}
function showModePage(mode){
  mount(el(`<div class="mobile-shell">${topbar(mode,'Free Fire contest mode')}<main class="page">
    <button class="back-link" onclick="openFreeFireModes()">${icon('back',20)} All modes</button>
    <div id="modeContent"></div>
  </main>${bottomNav('home')}</div>`));
  showMode(mode);
}
function showMode(mode){
  const wrap=document.querySelector('#modeContent');if(!wrap)return;
  const list=db.tournaments.filter(t=>t.mode===mode);
  wrap.innerHTML=`<div class="section-head"><div><h2>${mode}</h2><p>Everything in one place</p></div><span class="tag">${list.length} events</span></div><div class="tabs"><button id="tabLive" class="tab active" onclick="filterMode('${mode.replace(/'/g,"\\'")}','live')">Live</button><button id="tabUp" class="tab" onclick="filterMode('${mode.replace(/'/g,"\\'")}','upcoming')">Upcoming</button><button id="tabRes" class="tab" onclick="filterMode('${mode.replace(/'/g,"\\'")}','result')">Results</button></div><div id="modeList" class="tournament-grid"></div>`;
  filterMode(mode,'live')
}
function filterMode(mode,status){
 const map={live:'tabLive',upcoming:'tabUp',result:'tabRes'};['tabLive','tabUp','tabRes'].forEach(id=>document.getElementById(id)?.classList.remove('active'));document.getElementById(map[status])?.classList.add('active');
 const list=db.tournaments.filter(t=>t.mode===mode&&t.status===status);const target=document.querySelector('#modeList');if(!target)return;target.innerHTML=list.length?list.map(tournamentCard).join(''):`<div class="empty">No ${status==='result'?'results':status+' tournaments'} for ${mode} right now.</div>`;
}
function tournamentCard(t){
 const pct=Math.round((t.taken/t.total)*100);const statusClass=t.status==='live'?'live':t.status==='result'?'result':'upcoming';const label=t.status==='live'?'LIVE':t.status==='result'?'RESULTS':'UPCOMING';
 const action=t.status==='upcoming'?`<button class="btn btn-primary" style="flex:1" onclick="openJoin('${t.id}')">Join</button><button class="btn btn-secondary" onclick="openTournament('${t.id}')">Details</button>`:`<button class="btn btn-secondary btn-wide" onclick="openTournament('${t.id}')">${t.status==='live'?'Open live match':'View results'}</button>`;
 return `<article class="tournament-card"><div class="tc-top"><div><div class="tc-name">${t.name}</div><div class="small" style="margin-top:3px">${t.start} • ${t.id}</div></div><span class="status ${statusClass}">${label}</span></div><div class="tc-meta"><span class="meta">Entry <b>${money(t.entry)}</b></span><span class="meta">Kill <b>${money(t.kill)}</b></span><span class="meta">Prize <b>${money(t.prize)}</b></span></div><div class="tc-stats"><div class="stat-box"><div class="label">Slots</div><div class="value">${t.total}</div></div><div class="stat-box"><div class="label">Available</div><div class="value">${Math.max(t.total-t.taken,0)}</div></div><div class="stat-box"><div class="label">Filled</div><div class="value">${pct}%</div></div></div><div class="progress"><i style="width:${pct}%"></i></div><div class="tc-actions">${action}</div></article>`
}
function openTournament(id){const t=db.tournaments.find(x=>x.id===id);if(!t)return;ensureDataModel();const joined=db.joined.some(j=>j.tId===id);showModal(t.name,`<div class="grid2"><div class="panel"><div class="label-sm">Entry fee</div><div class="big-value">${money(t.entry)}</div></div><div class="panel"><div class="label-sm">Winning prize</div><div class="big-value">${money(t.prize)}</div></div></div><div class="panel" style="margin-top:12px"><div class="row"><span class="small">Per kill prize</span><b>${money(t.kill)}</b></div><div class="row" style="margin-top:10px"><span class="small">Slots</span><b>${t.taken}/${t.total}</b></div><div class="row" style="margin-top:10px"><span class="small">Schedule</span><b>${t.start}</b></div></div>${t.status==='live'?`<div class="success-box" style="margin-top:12px">Room ID: <b>${t.roomId}</b> &nbsp; Password: <b>${t.roomPass}</b></div>`:''}${joined?`<div class="grid2" style="margin-top:12px"><button class="btn btn-secondary" onclick="closeModal();openContestChart('${t.id}')">📊 Chart</button><button class="btn btn-primary" onclick="closeModal();openContestChat('${t.id}')">💬 Chat</button></div>`:''}${t.status==='result'?`<div class="panel" style="margin-top:12px"><b>Results published by admin</b><p class="small">Open the contest chart to see the final bracket and leaderboard.</p></div>`:''}${!joined&&t.status==='upcoming'?`<button class="btn btn-primary btn-wide" style="margin-top:12px" onclick="closeModal();openJoin('${t.id}')">Join tournament</button>`:''}`)}
function openContestChart(tId){const t=db.tournaments.find(x=>x.id===tId);if(!t)return;ensureDataModel();const joined=db.joined.some(j=>j.tId===tId);if(!joined&&db.session?.role!=='admin')return toast('Join this contest to access the chart');renderContestChart(tId)}
function renderContestChart(tId){const t=db.tournaments.find(x=>x.id===tId);if(!t)return;ensureDataModel();mount(el(`<div class="mobile-shell">${topbar(t.name,'Contest chart & bracket')}<main class="page"><button class="back-link" onclick="renderContests()">${icon('back',20)} Back to My Contests</button><section class="section-banner"><div><div class="tag">${t.mode}</div><h1>Chart Panel</h1><p>See the match path, live scores and final standings.</p></div><div class="ff-emblem big">CH</div></section><div class="tabs"><button id="chartOverview" class="tab active" onclick="chartTab('overview','${t.id}')">Overview</button><button id="chartBracket" class="tab" onclick="chartTab('bracket','${t.id}')">Chart</button><button id="chartBoard" class="tab" onclick="chartTab('leaderboard','${t.id}')">Leaderboard</button></div><div id="chartBody"></div></main>${bottomNav('contests')}</div>`));chartTab('overview',t.id)}
function chartTab(kind,id){const map={overview:'chartOverview',bracket:'chartBracket',leaderboard:'chartBoard'};Object.values(map).forEach(x=>document.getElementById(x)?.classList.remove('active'));document.getElementById(map[kind])?.classList.add('active');const t=db.tournaments.find(x=>x.id===id);if(!t)return;const c=t.chart||{};const box=document.getElementById('chartBody');if(!box)return;if(kind==='overview'){const activeRound=(c.rounds||[]).find(r=>(r.matches||[]).some(m=>m.status==='live'))||(c.rounds||[])[0];box.innerHTML=`<div class="grid2"><div class="panel"><div class="label-sm">Status</div><div class="big-value" style="font-size:18px">${t.status.toUpperCase()}</div></div><div class="panel"><div class="label-sm">Players</div><div class="big-value" style="font-size:18px">${t.taken}/${t.total}</div></div></div><div class="panel" style="margin-top:12px"><div class="section-head" style="margin:0 0 10px"><div><h3>${activeRound?.name||'Round 1'}</h3><p>Current contest progress</p></div><span class="tag">${activeRound?.matches?.length||0} matches</span></div>${(activeRound?.matches||[]).map(m=>`<div class="match-row"><div><b>${m.a}</b><span class="vs">vs</span><b>${m.b}</b><div class="small" style="margin-top:4px">${m.status==='live'?'Live match':'Scheduled'}</div></div><div class="score">${m.as} - ${m.bs}</div></div>`).join('')}</div><button class="btn btn-primary btn-wide" style="margin-top:12px" onclick="chartTab('bracket','${t.id}')">View Full Chart</button>`}else if(kind==='bracket'){box.innerHTML=`<div class="chart-rounds">${(c.rounds||[]).map(r=>`<section class="chart-round"><div class="chart-round-title">${r.name}</div>${(r.matches||[]).map(m=>`<div class="bracket-match"><div class="match-team"><span>${m.a}</span><b>${m.as}</b></div><div class="match-team"><span>${m.b}</span><b>${m.bs}</b></div><div class="small" style="margin-top:6px">${m.status==='live'?'🔴 LIVE':m.status==='done'?'Completed':'Upcoming'}</div></div>`).join('')}</section>`).join('')}</div>`}else{box.innerHTML=`<div class="panel"><table class="data-table"><thead><tr><th>#</th><th>Team / Player</th><th>Kills</th><th>Points</th></tr></thead><tbody>${(c.leaderboard||[]).map(r=>`<tr><td>${r.position}</td><td><b>${r.name}</b></td><td>${r.kills}</td><td>${r.points}</td></tr>`).join('')}</tbody></table></div>`}}
function openJoin(id){const t=db.tournaments.find(x=>x.id===id);if(t.taken>=t.total)return toast('This tournament is full');if(db.user.balance<t.entry)return showModal('Not enough coins',`<div class="alert">Your wallet has ${money(db.user.balance)}. You need ${money(t.entry)} to join.</div><button class="btn btn-primary btn-wide" onclick="closeModal();go('wallet')">Add coins</button>`);showJoinFlow(t)}
function showJoinFlow(t){showModal('Join '+t.name,`<div class="small" style="margin-bottom:10px">Choose your player details and a free slot.</div><div class="field"><label>Game UID</label><input id="joinUid" placeholder="Enter your Free Fire UID"></div><div class="field"><label>Choose slot</label><div class="slot-grid" id="slots">${Array.from({length:Math.min(t.total,40)},(_,i)=>{const n=i+1;const taken=n<=t.taken;return `<button class="slot ${taken?'taken':''}" ${taken?'disabled':''} onclick="selectSlot(${n})">${n}</button>`}).join('')}</div></div><div id="slotHint" class="small" style="margin-top:10px">Select one available slot.</div><button class="btn btn-primary btn-wide" style="margin-top:14px" onclick="confirmJoin('${t.id}')">Confirm & pay ${money(t.entry)}</button>`)}
let selectedSlot=null;
function selectSlot(n){selectedSlot=n;document.querySelectorAll('.slot').forEach(x=>x.classList.toggle('selected',Number(x.textContent)===n));document.querySelector('#slotHint').textContent=`Slot ${n} selected`}
function confirmJoin(id){const uid=document.querySelector('#joinUid').value.trim();if(!uid)return toast('Enter your game UID');if(!selectedSlot)return toast('Choose a slot');const t=db.tournaments.find(x=>x.id===id);if(db.user.balance<t.entry)return toast('Wallet balance is insufficient');const chosen=selectedSlot;db.user.balance-=t.entry;t.taken+=1;db.joined.unshift({tId:id,status:'upcoming',slot:chosen,uid,joinedAt:'Just now'});db.transactions.unshift({type:'Debit',amount:t.entry,details:`Joined ${t.name}`,status:'completed',date:'Today'});notify('join','Tournament joined',`You joined ${t.name} in slot ${chosen}.` ,{tId:id});if(t.total-t.taken<=10) notify('slots','Limited slots remaining',`${t.name} now has ${Math.max(t.total-t.taken,0)} slots left.`,{tId:id});selectedSlot=null;save();closeModal();toast(`Joined successfully • Slot ${chosen}`);showModePage(t.mode)}
function renderContests(){mount(el(`<div class="mobile-shell">${topbar('My Contests','Your tournament activity')}<main class="page"><div class="tabs"><button class="tab active" id="ctUp" onclick="contestTab('up')">Upcoming</button><button class="tab" id="ctRes" onclick="contestTab('res')">Results</button></div><div id="contestList"></div></main>${bottomNav('contests')}</div>`));contestTab('up')}
function contestTab(kind){document.getElementById('ctUp')?.classList.toggle('active',kind==='up');document.getElementById('ctRes')?.classList.toggle('active',kind==='res');const box=document.getElementById('contestList');if(!box)return;if(kind==='up'){const rows=db.joined.filter(j=>j.status==='upcoming'||j.status==='live');box.innerHTML=rows.length?rows.map(j=>{const t=db.tournaments.find(x=>x.id===j.tId);return `<div class="tournament-card" style="margin-bottom:10px"><div class="tc-top"><div><div class="tc-name">${t?.name||j.tId}</div><div class="small">Slot ${j.slot} • UID ${j.uid}</div></div><span class="status ${j.status==='live'?'live':'upcoming'}">${j.status}</span></div>${j.status==='live'?`<div class="success-box" style="margin-top:10px">Room ID: <b>${t.roomId}</b> &nbsp; Password: <b>${t.roomPass}</b></div>`:''}<div class="tc-actions" style="margin-top:10px"><button class="btn btn-secondary" onclick="openContestChart('${j.tId}')">📊 Chart</button><button class="btn btn-primary" onclick="openContestChat('${j.tId}')">💬 Contest Chat</button></div></div>`}).join(''):`<div class="empty">You have not joined any upcoming tournament.</div>`}else{box.innerHTML=db.results.length?db.results.map(r=>`<div class="tournament-card" style="margin-bottom:10px"><div class="tc-top"><div><div class="tc-name">${r.title}</div><div class="small">${r.date} • ${r.tId}</div></div><span class="status result">#${r.position}</span></div><div class="tc-meta"><span class="meta">Kills <b>${r.kills}</b></span><span class="meta">Prize <b>${money(r.prize)}</b></span></div></div>`).join(''):`<div class="empty">No published results yet.</div>`}}
function chatMessages(tId){ensureDataModel();return Array.isArray(db.contestChats[tId])?db.contestChats[tId]:[]}
function openContestChat(tId){const t=db.tournaments.find(x=>x.id===tId);if(!t)return;const joined=db.joined.some(j=>j.tId===tId);if(!joined && db.session?.role!=='admin')return toast('Join this contest to access its chat');renderContestChat(tId)}
function renderContestChat(tId){const t=db.tournaments.find(x=>x.id===tId);if(!t)return;const msgs=chatMessages(tId);showModal(`💬 ${t.name}`,`<div class="chat-meta"><span class="tag">${t.mode}</span><span class="small">Contest chat • ${t.id}</span></div><div id="chatThread" class="chat-thread">${msgs.length?msgs.map(m=>`<div class="chat-bubble ${m.from==='admin'?'admin-bubble':'user-bubble'}"><div class="chat-author">${m.name|| (m.from==='admin'?'Admin':'You')}</div><div>${m.message}</div><div class="chat-time">${formatTime(m.time)}</div></div>`).join(''):`<div class="empty">No messages yet. Ask the admin about room details, timing or contest rules.</div>`}</div><div class="chat-compose"><input id="contestChatInput" placeholder="Message the admin..." onkeydown="if(event.key==='Enter')sendContestChat('${tId}')"><button class="btn btn-primary" onclick="sendContestChat('${tId}')">Send</button></div><div class="small" style="margin-top:8px">Room ID/password can be posted here by the admin for this specific contest.</div>`);setTimeout(()=>{const box=document.querySelector('#chatThread');if(box)box.scrollTop=box.scrollHeight},0)}
function sendContestChat(tId){const input=document.querySelector('#contestChatInput');const msg=input?.value.trim();if(!msg)return;ensureDataModel();db.contestChats[tId]=db.contestChats[tId]||[];db.contestChats[tId].push({id:'M'+Date.now(),from:'user',name:db.user.name||'You',message:msg,time:Date.now()});save();input.value='';renderContestChat(tId)}
function adminContestChatView(tId){const t=db.tournaments.find(x=>x.id===tId);if(!t)return;const msgs=chatMessages(tId);return `<div class="section-head"><div><h2>${t.name}</h2><p>${t.mode} • ${t.id} • ${t.taken}/${t.total} slots</p></div><span class="tag">Contest chat</span></div><div class="chat-thread admin-thread">${msgs.length?msgs.map(m=>`<div class="chat-bubble ${m.from==='admin'?'admin-bubble':'user-bubble'}"><div class="chat-author">${m.name|| (m.from==='admin'?'Admin':'User')}</div><div>${m.message}</div><div class="chat-time">${formatTime(m.time)}</div></div>`).join(''):`<div class="empty">No chat messages for this contest yet.</div>`}</div><div class="chat-compose"><input id="adminChatInput" placeholder="Send room ID, password, reminder or reply..."><button class="btn btn-primary" onclick="sendAdminContestChat('${t.id}')">Reply</button></div>`}
function sendAdminContestChat(tId){const input=document.querySelector('#adminChatInput');const msg=input?.value.trim();if(!msg)return;ensureDataModel();db.contestChats[tId]=db.contestChats[tId]||[];db.contestChats[tId].push({id:'M'+Date.now(),from:'admin',name:'Admin',message:msg,time:Date.now()});const t=db.tournaments.find(x=>x.id===tId);notify('admin','New contest chat message',`Admin posted a message in ${t?.name||tId}.`,{tId});save();toast('Reply sent');adminView('contestChats')}
function renderWallet(){mount(el(`<div class="mobile-shell">${topbar('Wallet','Coins & payment status')}<main class="page"><section class="hero"><div class="label-sm">Available balance</div><div class="big-value" style="font-size:40px">${money(db.user.balance)}</div><div class="tc-actions"><button class="btn btn-primary" style="flex:1" onclick="openDeposit()">＋ Add coins</button><button class="btn btn-secondary" style="flex:1" onclick="openWithdraw()">Withdraw</button></div></section><div class="section-head"><div><h2>Transactions</h2><p>Wallet activity and verification status</p></div></div><div class="panel">${db.transactions.slice(0,12).map(x=>`<div class="row" style="padding:10px 0;border-bottom:1px solid var(--line)"><div><b>${x.details}</b><div class="small">${x.date} • ${x.status}</div></div><strong style="color:${x.type==='Credit'?'var(--success)':'#ff929b'}">${x.type==='Credit'?'+':'-'}${money(x.amount)}</strong></div>`).join('')||'<div class="empty">No transactions</div>'}</div><div class="section-head"><div><h2>Support</h2><p>Need help with a payment or tournament?</p></div></div><div class="panel"><div class="support-link"><span>Admin email</span><a class="link" href="mailto:${db.admin.email}">${db.admin.email}</a></div><div class="support-link"><span>Telegram</span><span class="link">${db.admin.telegram}</span></div><div class="support-link"><span>Chat support</span><button class="btn btn-secondary" onclick="openSupport()">Open chat</button></div></div></main>${bottomNav('wallet')}</div>`))}
function openDeposit(){showModal('Add coins',`<div class="alert">Choose an amount. The prototype creates a payment request and marks it <b>Pending verification</b> until admin approval.</div><div class="field"><label>Amount</label><input id="depositAmt" type="number" min="1" placeholder="e.g. 100"></div><div class="panel" style="margin-bottom:12px"><div class="small">Admin UPI ID</div><div style="font-weight:900;margin-top:4px">${db.admin.upi}</div></div><button class="btn btn-primary btn-wide" onclick="createDeposit()">Generate UPI payment QR</button>`)}
function createDeposit(){const amt=Number(document.querySelector('#depositAmt').value);if(!amt||amt<=0)return toast('Enter a valid amount');const ref='PAY'+Math.floor(100000+Math.random()*899999);db.deposits.unshift({id:ref,amount:amt,status:'pending',date:'Today'});notify('wallet','Add money request submitted',`${money(amt)} is pending admin verification.`);save();document.querySelector('.sheet').innerHTML=`<div class="sheet-head"><h3>Payment request</h3><button class="icon-btn" onclick="closeModal()">×</button></div><div class="qr"></div><div class="panel"><div class="row"><span>Amount</span><b>${money(amt)}</b></div><div class="row" style="margin-top:10px"><span>UPI</span><b>${db.admin.upi}</b></div><div class="row" style="margin-top:10px"><span>Reference</span><b>${ref}</b></div></div><div class="alert" style="margin-top:12px">After payment, your request stays pending until the admin verifies the transaction.</div><button class="btn btn-primary btn-wide" style="margin-top:12px" onclick="closeModal();toast('Payment marked pending verification');renderWallet()">I paid</button>`}
function openWithdraw(){showModal('Withdraw coins',`<div class="alert">Minimum withdrawal amount is <b>₹100</b>. Requests remain pending until admin verification.</div><div class="field"><label>Amount</label><input id="withdrawAmt" type="number" min="100" placeholder="Minimum 100"></div><div class="field"><label>Bank / UPI details</label><input id="withdrawDest" placeholder="UPI ID or bank account"></div><button class="btn btn-primary btn-wide" onclick="createWithdraw()">Submit withdrawal</button>`)}
function createWithdraw(){const amt=Number(document.querySelector('#withdrawAmt').value);const dest=document.querySelector('#withdrawDest').value.trim();if(amt<100)return toast('Minimum withdrawal is ₹100');if(amt>db.user.balance)return toast('Insufficient balance');if(!dest)return toast('Enter payout details');db.user.balance-=amt;db.withdrawals.unshift({id:'WD'+Date.now(),amount:amt,dest,status:'pending',date:'Today'});db.transactions.unshift({type:'Debit',amount:amt,details:'Withdrawal request',status:'pending',date:'Today'});notify('withdraw','Withdrawal request submitted',`${money(amt)} is pending admin verification.`);save();closeModal();toast('Withdrawal submitted for verification');renderWallet()}
function renderNotifications(){
  ensureDataModel(); upcomingReminderCheck(); slotUpdateCheck();
  db.notifications.forEach(n=>n.read=true); save();
  const groups={Today:[],Earlier:[]}; const now=new Date();
  (db.notifications||[]).forEach(n=>{const d=new Date(n.time); const same=d.toDateString()===now.toDateString(); groups[same?'Today':'Earlier'].push(n)});
  mount(el(`<div class="mobile-shell">${topbar('Notifications','Tournament and account updates')}<main class="page">
    <button class="back-link" onclick="go('home')">${icon('back',20)} Back to Home</button>
    <section class="section-banner"><div><div class="tag">UPDATES</div><h1>Notifications</h1><p>Stay updated about tournaments, joins, wallet activity and admin announcements.</p></div><div class="ff-emblem big">N</div></section>
    ${['Today','Earlier'].map(g=>groups[g].length?`<div class="section-head"><div><h2>${g}</h2></div></div><div class="notification-list">${groups[g].map(notificationCard).join('')}</div>`:'').join('')}
    ${!db.notifications.length?'<div class="empty">You are all caught up.</div>':''}
  </main>${bottomNav('home')}</div>`));
}
function notificationCard(n){return `<button class="notification-card" onclick="openNotification('${n.id}')"><div class="notification-icon ${n.type}">${notificationIcon(n.type)}</div><div class="notification-body"><div class="notification-top"><b>${n.title}</b><span class="small">${formatTime(n.time)}</span></div><p>${n.message}</p></div></button>`}
function openNotification(id){const n=db.notifications.find(x=>x.id===id);if(!n)return;if(n.tId){const t=db.tournaments.find(x=>x.id===n.tId);if(t){closeModal();openTournament(t.id);return}}showModal(n.title,`<div class="panel"><div class="small">${formatTime(n.time)}</div><p style="margin:8px 0 0;color:#cbd2dd;line-height:1.5">${n.message}</p></div>`)}
function renderProfile(){mount(el(`<div class="mobile-shell">${topbar('Profile','Your Gaming Arena identity')}<main class="page"><section class="panel" style="padding:18px"><div class="row"><div><div class="tag">PLAYER</div><h2 style="margin:8px 0 3px">${db.user.name}</h2><div class="small">${db.user.email}</div></div><div class="brand-mark" style="width:48px;height:48px">GA</div></div><hr><div class="grid3"><div><div class="label-sm">UID</div><div class="big-value" style="font-size:16px">${db.user.uid||'—'}</div></div><div><div class="label-sm">Played</div><div class="big-value" style="font-size:16px">${db.user.played}</div></div><div><div class="label-sm">Kills</div><div class="big-value" style="font-size:16px">${db.user.kills}</div></div></div></section><div class="grid2" style="margin-top:12px"><div class="panel"><div class="label-sm">Wins</div><div class="big-value">${db.user.wins}</div></div><div class="panel"><div class="label-sm">Winnings</div><div class="big-value">${money(db.user.winnings)}</div></div></div><div class="section-head"><div><h2>Account</h2><p>Manage your profile</p></div></div><div class="panel"><button class="btn btn-secondary btn-wide" onclick="editProfile()">Edit profile</button><button class="btn btn-secondary btn-wide" style="margin-top:8px" onclick="openSupport()">Customer support</button><button class="btn btn-danger btn-wide" style="margin-top:8px" onclick="logout()">Logout</button></div></main>${bottomNav('profile')}</div>`))}
function editProfile(){showModal('Edit profile',`<div class="field"><label>Name</label><input id="editName" value="${db.user.name}"></div><div class="field"><label>Free Fire UID</label><input id="editUid" value="${db.user.uid}"></div><button class="btn btn-primary btn-wide" onclick="saveProfile()">Save changes</button>`)}
function saveProfile(){db.user.name=document.querySelector('#editName').value.trim()||db.user.name;db.user.uid=document.querySelector('#editUid').value.trim();save();closeModal();toast('Profile updated');renderProfile()}
function openSupport(){showModal('Customer support',`<div class="panel"><div class="support-link"><span>Email</span><a href="mailto:${db.admin.email}" class="link">${db.admin.email}</a></div><div class="support-link"><span>Telegram</span><span class="link">${db.admin.telegram}</span></div></div><div class="field"><label>Message</label><input id="supportMsg" placeholder="How can we help?"></div><button class="btn btn-primary btn-wide" onclick="toast('Message sent to admin support');closeModal()">Send message</button>`)}
function showModal(title,body){const o=el(`<div class="overlay show" id="overlay"><div class="sheet"><div class="sheet-head"><h3>${title}</h3><button class="icon-btn" onclick="closeModal()">×</button></div>${body}</div></div>`);document.body.appendChild(o);o.addEventListener('click',e=>{if(e.target===o)closeModal()})}
function closeModal(){document.getElementById('overlay')?.remove()}
function logout(){db.session=null;save();renderAuth()}
function renderAdmin(){
  const node=el(`<div class="admin-shell"><div class="admin-layout"><aside class="admin-sidebar"><div class="brand"><span class="brand-mark">GA</span><span>Admin</span></div><div class="small" style="margin-top:5px">Gaming Arena control room</div><div class="admin-nav"><button class="active" data-a="dashboard" onclick="adminView('dashboard')">Dashboard</button><button data-a="tournaments" onclick="adminView('tournaments')">Tournaments</button><button data-a="users" onclick="adminView('users')">Users & joins</button><button data-a="wallet" onclick="adminView('wallet')">Wallet queue</button><button data-a="support" onclick="adminView('support')">Support</button><button data-a="contestChats" onclick="adminView('contestChats')">Contest chats</button><button data-a="charts" onclick="adminView('charts')">Charts / Brackets</button><button data-a="notifications" onclick="adminView('notifications')">Notifications</button><button onclick="logout()">Logout</button></div></aside><main class="admin-main"><div class="admin-mobile-head"><div class="brand"><span class="brand-mark">GA</span><span>Admin</span></div><button class="icon-btn" onclick="logout()">×</button></div><div id="adminContent"></div></main></div></div>`);mount(node);adminView('dashboard')
}
function adminView(view){document.querySelectorAll('.admin-nav button[data-a]').forEach(b=>b.classList.toggle('active',b.dataset.a===view));const box=document.querySelector('#adminContent');if(!box)return; if(view==='dashboard')box.innerHTML=adminDashboard(); if(view==='tournaments')box.innerHTML=adminTournaments(); if(view==='users')box.innerHTML=adminUsers(); if(view==='wallet')box.innerHTML=adminWallet(); if(view==='support')box.innerHTML=adminSupport(); if(view==='contestChats')box.innerHTML=adminContestChats(); if(view==='charts')box.innerHTML=adminCharts(); if(view==='notifications')box.innerHTML=adminNotifications()}
function adminDashboard(){const pending=db.deposits.filter(x=>x.status==='pending').length+db.withdrawals.filter(x=>x.status==='pending').length;return `<div class="section-head" style="margin-top:0"><div><h2>Dashboard</h2><p>Live control over Gaming Arena</p></div><span class="tag">Admin only</span></div><div class="admin-cards"><div class="panel"><div class="label-sm">Tournaments</div><div class="big-value">${db.tournaments.length}</div></div><div class="panel"><div class="label-sm">Joined entries</div><div class="big-value">${db.joined.length}</div></div><div class="panel"><div class="label-sm">Pending wallet</div><div class="big-value">${pending}</div></div><div class="panel"><div class="label-sm">Balance in demo</div><div class="big-value">${money(db.user.balance)}</div></div></div><div class="section-head"><div><h3>Quick actions</h3><p>Manage the game from one place</p></div></div><div class="grid2"><button class="btn btn-primary" onclick="adminView('tournaments')">Create tournament</button><button class="btn btn-secondary" onclick="adminView('wallet')">Verify wallet</button><button class="btn btn-secondary" onclick="adminView('charts')">Update charts</button></div>`}
function adminTournaments(){return `<div class="section-head" style="margin-top:0"><div><h2>Tournaments</h2><p>Create, edit, start, finish and publish results.</p></div><button class="btn btn-primary" onclick="openAdminTournament()">＋ New</button></div><div class="panel" style="overflow:auto"><table class="data-table"><thead><tr><th>Name</th><th>Mode</th><th>Status</th><th>Slots</th><th>Action</th></tr></thead><tbody>${db.tournaments.map(t=>`<tr><td><b>${t.name}</b><div class="small">${t.id}</div></td><td>${t.mode}</td><td>${t.status}</td><td>${t.taken}/${t.total}</td><td><div class="tc-actions"><button class="btn btn-secondary" onclick="openAdminTournament('${t.id}')">Edit</button><button class="btn btn-secondary" onclick="adminEditChart('${t.id}')">Chart</button></div></td></tr>`).join('')}</tbody></table></div>`}
function openAdminTournament(id=''){const t=id?db.tournaments.find(x=>x.id===id):{id:'',name:'',mode:'BR Solo',status:'upcoming',start:'Tomorrow • 8 PM',entry:20,kill:10,prize:500,total:48,taken:0,roomId:'—',roomPass:'—'};showModal(id?'Edit tournament':'Create tournament',`<div class="grid2"><div class="field"><label>Name</label><input id="aName" value="${t.name}"></div><div class="field"><label>Mode</label><select id="aMode">${MODES.map(m=>`<option ${m===t.mode?'selected':''}>${m}</option>`).join('')}</select></div></div><div class="grid2"><div class="field"><label>Status</label><select id="aStatus"><option ${t.status==='upcoming'?'selected':''}>upcoming</option><option ${t.status==='live'?'selected':''}>live</option><option ${t.status==='result'?'selected':''}>result</option></select></div><div class="field"><label>Schedule</label><input id="aStart" value="${t.start}"></div></div><div class="grid3"><div class="field"><label>Entry</label><input id="aEntry" type="number" value="${t.entry}"></div><div class="field"><label>Per kill</label><input id="aKill" type="number" value="${t.kill}"></div><div class="field"><label>Prize</label><input id="aPrize" type="number" value="${t.prize}"></div></div><div class="grid2"><div class="field"><label>Total slots</label><input id="aTotal" type="number" value="${t.total}"></div><div class="field"><label>Room ID</label><input id="aRoom" value="${t.roomId}"></div></div><div class="field"><label>Room password</label><input id="aPass" value="${t.roomPass}"></div><button class="btn btn-primary btn-wide" onclick="saveAdminTournament('${id}')">Save tournament</button>`)}
function saveAdminTournament(id){const obj={id:id||'GA-'+Math.floor(1000+Math.random()*8999),name:document.querySelector('#aName').value||'Untitled Tournament',mode:document.querySelector('#aMode').value,status:document.querySelector('#aStatus').value,start:document.querySelector('#aStart').value,entry:Number(document.querySelector('#aEntry').value),kill:Number(document.querySelector('#aKill').value),prize:Number(document.querySelector('#aPrize').value),total:Number(document.querySelector('#aTotal').value),taken:id?db.tournaments.find(x=>x.id===id).taken:0,roomId:document.querySelector('#aRoom').value||'—',roomPass:document.querySelector('#aPass').value||'—'};if(id){const i=db.tournaments.findIndex(x=>x.id===id);db.tournaments[i]=obj;notify('admin','Tournament updated by admin',`${obj.name} has been updated. Check the tournament details for the latest schedule, prizes and slots.`,{tId:obj.id})}else{db.tournaments.unshift(obj);notify('tournament','New tournament added',`${obj.name} is now available in ${obj.mode}. Entry ${money(obj.entry)} • ${obj.total} total slots.`,{tId:obj.id})}save();closeModal();toast('Tournament saved');adminView('tournaments')}
function adminUsers(){return `<div class="section-head" style="margin-top:0"><div><h2>Users & joins</h2><p>Player identity and contest entries</p></div></div><div class="panel"><div class="row"><div><b>${db.user.name}</b><div class="small">${db.user.email} • UID ${db.user.uid||'not set'}</div></div><div class="tag">Demo user</div></div><hr>${db.joined.map(j=>{const t=db.tournaments.find(x=>x.id===j.tId);return `<div class="row" style="padding:10px 0;border-bottom:1px solid var(--line)"><div><b>${t?.name||j.tId}</b><div class="small">Slot ${j.slot} • UID ${j.uid}</div></div><span class="tag">${j.status}</span></div>`}).join('')}</div>`}
function adminWallet(){return `<div class="section-head" style="margin-top:0"><div><h2>Wallet queue</h2><p>Approve deposits and withdrawals</p></div><button class="btn btn-secondary" onclick="openAdminUPI()">UPI settings</button></div><div class="panel"><h3 style="margin-top:0">Deposits</h3>${db.deposits.length?db.deposits.map(d=>`<div class="row" style="padding:10px 0;border-bottom:1px solid var(--line)"><div><b>${money(d.amount)}</b><div class="small">${d.id} • ${d.status}</div></div>${d.status==='pending'?`<button class="btn btn-primary" onclick="approveDeposit('${d.id}')">Approve</button>`:''}</div>`).join(''):'<div class="empty">No deposit requests.</div>'}<h3>Withdrawals</h3>${db.withdrawals.length?db.withdrawals.map(w=>`<div class="row" style="padding:10px 0;border-bottom:1px solid var(--line)"><div><b>${money(w.amount)}</b><div class="small">${w.dest} • ${w.status}</div></div>${w.status==='pending'?`<button class="btn btn-primary" onclick="approveWithdraw('${w.id}')">Approve</button>`:''}</div>`).join(''):'<div class="empty">No withdrawals.</div>'}</div>`}
function approveDeposit(id){const d=db.deposits.find(x=>x.id===id);if(!d)return;d.status='approved';db.user.balance+=d.amount;db.transactions.unshift({type:'Credit',amount:d.amount,details:'Deposit approved',status:'completed',date:'Today'});notify('wallet','Add money approved',`${money(d.amount)} has been added to your wallet.`);save();toast('Deposit approved');adminView('wallet')}
function approveWithdraw(id){const w=db.withdrawals.find(x=>x.id===id);if(!w)return;w.status='approved';db.transactions.push({type:'Debit',amount:w.amount,details:'Withdrawal approved',status:'completed',date:'Today'});notify('withdraw','Withdrawal approved',`${money(w.amount)} withdrawal has been approved by admin.`);save();toast('Withdrawal approved');adminView('wallet')}
function openAdminUPI(){showModal('UPI settings',`<div class="field"><label>Admin UPI ID</label><input id="adminUpi" value="${db.admin.upi}"></div><div class="field"><label>Support email</label><input id="adminEmail" value="${db.admin.email}"></div><div class="field"><label>Telegram</label><input id="adminTelegram" value="${db.admin.telegram}"></div><button class="btn btn-primary btn-wide" onclick="saveAdminUPI()">Save settings</button>`)}
function saveAdminUPI(){db.admin.upi=document.querySelector('#adminUpi').value;db.admin.email=document.querySelector('#adminEmail').value;db.admin.telegram=document.querySelector('#adminTelegram').value;save();closeModal();toast('Settings saved')}
function adminContestChats(){const joinedIds=[...new Set((db.joined||[]).map(j=>j.tId))];const liveIds=db.tournaments.filter(t=>t.status==='live').map(t=>t.id);const ids=[...new Set([...joinedIds,...liveIds])];const selected=window.__adminChatTid&&db.tournaments.find(t=>t.id===window.__adminChatTid)?window.__adminChatTid:(ids[0]||db.tournaments[0]?.id);if(!selected)return '<div class="empty">Create or join a tournament to start a contest chat.</div>';const t=db.tournaments.find(x=>x.id===selected);return `<div class="section-head"><div><h2>Contest chats</h2><p>Each match/tournament has its own private user + admin thread.</p></div></div><div class="grid2"><div class="panel"><div class="small">Select contest</div><select id="adminChatSelect" onchange="window.__adminChatTid=this.value;adminView('contestChats')">${ids.map(i=>{const x=db.tournaments.find(t=>t.id===i);return `<option value="${i}" ${i===selected?'selected':''}>${x?.name||i}</option>`}).join('')}</select><div style="margin-top:12px">${t?`<div class="label-sm">${t.mode} • ${t.id}</div><div class="small" style="margin-top:5px">${t.taken}/${t.total} slots filled</div>`:''}</div></div><div class="panel">${adminContestChatView(selected)}</div></div>`}
function adminCharts(){ensureDataModel();return `<div class="section-head" style="margin-top:0"><div><h2>Charts / Brackets</h2><p>Admin updates the chart every contest player can see.</p></div></div><div class="panel">${db.tournaments.map(t=>`<div class="row" style="padding:12px 0;border-bottom:1px solid var(--line)"><div><b>${t.name}</b><div class="small">${t.mode} • ${t.status}</div></div><button class="btn btn-primary" onclick="adminEditChart('${t.id}')">Manage chart</button></div>`).join('')}</div>`}
function adminEditChart(id){const t=db.tournaments.find(x=>x.id===id);if(!t)return;ensureDataModel();const ms=(t.chart?.rounds?.[0]?.matches||[]).slice(0,4);showModal('Manage chart • '+t.name,`<div class="small" style="margin-bottom:10px">Change the first-round matchups and scores. These values are shown in the user chart.</div>${ms.map((m,i)=>`<div class="panel" style="margin-bottom:10px"><div class="grid2"><div class="field"><label>Team A</label><input id="a${i}" value="${m.a}"></div><div class="field"><label>Score</label><input id="as${i}" type="number" value="${m.as}"></div></div><div class="grid2"><div class="field"><label>Team B</label><input id="b${i}" value="${m.b}"></div><div class="field"><label>Score</label><input id="bs${i}" type="number" value="${m.bs}"></div></div><div class="field"><label>Status</label><select id="s${i}"><option value="scheduled" ${m.status==='scheduled'?'selected':''}>Upcoming</option><option value="live" ${m.status==='live'?'selected':''}>Live</option><option value="done" ${m.status==='done'?'selected':''}>Completed</option></select></div></div>`).join('')}<button class="btn btn-primary btn-wide" onclick="saveAdminChart('${id}',${ms.length})">Save chart updates</button>`)}
function saveAdminChart(id,count){const t=db.tournaments.find(x=>x.id===id);if(!t)return;ensureDataModel();const r=t.chart.rounds[0];for(let i=0;i<count;i++){r.matches[i].a=document.querySelector('#a'+i).value.trim();r.matches[i].b=document.querySelector('#b'+i).value.trim();r.matches[i].as=Number(document.querySelector('#as'+i).value)||0;r.matches[i].bs=Number(document.querySelector('#bs'+i).value)||0;r.matches[i].status=document.querySelector('#s'+i).value;}t.chart.updatedAt=Date.now();notify('admin','Contest chart updated',`${t.name} chart was updated by admin.`,{tId:t.id});save();closeModal();toast('Chart updated');adminView('charts')}
function adminNotifications(){return `<div class="section-head" style="margin-top:0"><div><h2>Notifications</h2><p>Send announcements and monitor automatic slot reminders.</p></div><button class="btn btn-primary" onclick="openAdminNotification()">＋ Send</button></div><div class="panel"><div class="small">Recent notifications</div>${(db.notifications||[]).slice(0,12).map(n=>`<div class="row" style="padding:12px 0;border-bottom:1px solid var(--line)"><div><b>${n.title}</b><div class="small">${formatTime(n.time)} • ${n.type}</div><div class="small" style="margin-top:3px">${n.message}</div></div></div>`).join('')||'<div class="empty">No notifications yet.</div>'}</div>`}
function openAdminNotification(){showModal('Send notification',`<div class="field"><label>Title</label><input id="nTitle" placeholder="Tournament update"></div><div class="field"><label>Message</label><textarea id="nMessage" rows="4" placeholder="Tell users about the tournament..." style="width:100%;border-radius:13px;border:1px solid var(--line);background:#0e1219;color:#fff;padding:12px;resize:vertical"></textarea></div><div class="field"><label>Type</label><select id="nType"><option value="admin">Admin announcement</option><option value="tournament">Tournament</option><option value="slots">Remaining slots</option></select></div><button class="btn btn-primary btn-wide" onclick="sendAdminNotification()">Send to users</button>`)}
function sendAdminNotification(){const title=document.querySelector('#nTitle').value.trim()||'Admin announcement';const message=document.querySelector('#nMessage').value.trim();const type=document.querySelector('#nType').value;if(!message)return toast('Enter a message');notify(type,title,message);closeModal();toast('Notification sent to users');adminView('notifications')}
function adminSupport(){return `<div class="section-head" style="margin-top:0"><div><h2>Support</h2><p>Customer support channels</p></div></div><div class="grid2"><div class="panel"><div class="label-sm">Email</div><div style="font-weight:900;margin-top:5px">${db.admin.email}</div></div><div class="panel"><div class="label-sm">Telegram</div><div style="font-weight:900;margin-top:5px">${db.admin.telegram}</div></div></div><div class="panel" style="margin-top:12px"><div class="success-box">Chat support is available in the user app. Messages can be connected to a real backend once deployed.</div></div>`}

// First paint
if(db.session?.role==='admin')renderAdmin(); else if(db.session?.role==='user')renderHome(); else renderAuth();
